#!/bin/bash

# expecting <userId>, <password> as arg.
if [ "$#" -ne 3]; then
    echo "Expecting args: <userId> <password> <email>"
    exit 1
fi

echo "Storing git creds" >> ${LOG_FILE}

userId=$1
password=$2
email=$3

cd ${BLOG_PATH}

git config --global user.email $email
git config --global user.name $userId

# unset & restore git credentials globally
git config --global --unset credential.helper
git config --global credential.helper store

expect ${SERVER_PATH}/scripts/expect/githubPublish.exp $userId $password

