#!/bin/bash

# expecting <blog-clone-url> as arg.
if [ "$#" -ne 1 ]; then
    echo "Expecting args: <blog-clone-url>"
    exit 1
fi

clone_url=$1

# goto blog dir and create post
cd ${C9_PATH}

# clone blog(code) repo
git clone --recursive ${clone_url} ${BLOG_PATH}
status=$?

# If BLOG_SOUCE is empty, then copy sample blog-source files.
[[ $(ls -A ${BLOG_PATH}) ]] || cp -r ${SERVER_PATH}/sample-blog-source/* ${BLOG_PATH}
cd -

# exit if git clone fails
if [[ $status -ne "0" ]];
then
    echo "unable to clone blog" >> ${LOG_FILE}
    exit $status
fi
